In [1]:
!uv pip install pandas

Resolved 4 packages in 128ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 14.26s
 + pandas==3.0.3

In [2]:
import pandas as pd

In [3]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [4]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [5]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [6]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [11]:
!uv pip install learntools.core

  × No solution found when resolving dependencies:
  ╰─▶ Because learntools-core was not found in the package registry and you
      require learntools-core, we can conclude that your requirements are
      unsatisfiable.

In [15]:
fruits = pd.DataFrame({'Apples': [30, 20], 'Bananas': [21, 10]})
fruits

   Apples  Bananas
0      30       21
1      20       10

In [21]:
fifa_players = pd.read_csv('fifa_world_cup_2026_player_performance.csv', index_col=0)
fifa_players.head()

,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,club_name,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
player_id,,,,,,,,,,,,,,,,,,,,,
P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,RB Salzburg,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,Chelsea,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,AIK,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,PSV Eindhoven,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,Juventus,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

In [24]:
## Midfielsers with good consistency
midfielders = fifa_players.loc[(fifa_players.position == 'Midfielder') & (fifa_players.consistency_score >= 75)]
midfielders

,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,club_name,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
player_id,,,,,,,,,,,,,,,,,,,,,
P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,AIK,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
P00072,Dani Gavi,21,Spanish,Spain,20,Midfielder,181,78,Right,Dinamo Zagreb,...,17.0,65.4,85.8,91.1,48.2,1,2,332,0,6.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P01002,Aymen Kasid,28,Iraqi,Iraq,14,Midfielder,181,75,Right,Ulsan HD,...,11.3,87.4,99.0,99.0,87.4,0,0,167,0,7.4
P01001,Mohannad Al-Saadi,29,Iraqi,Iraq,13,Midfielder,175,79,Right,Ulsan HD,...,2.8,84.2,73.9,87.6,89.7,2,0,216,0,6.1

In [29]:
fifa_players.weight_kg.describe()

count    54600.000000
mean        75.754853
             ...
75%         78.000000
max         87.000000
Name: weight_kg, Length: 8, dtype: float64

In [30]:
fifa_players.height_cm.describe()

count    54600.000000
mean       181.654341
             ...
75%        186.000000
max        200.000000
Name: height_cm, Length: 8, dtype: float64

In [31]:
fifa_players.weight_kg.median()

np.float64(76.0)